cc_binary(
	name = "trade",
	srcs = [
		"trade.cc",
	],
)

cc_library(
	name = "options_trader",
	srcs = [
		"options_trader.cc",
	],
	hdrs = [
		"options_trader.hh",
	],
	deps = [
		"//tradeable:option",
	]
)
