cc_library(
	name = "option",
	hdrs = [
		"option.hh",
	],
	deps = [
		"//common:price",
		"//common:ticker",
	],
	visibility = [
		"//options_trading:__subpackages__",
	],
)

cc_library(
	name = "stock",
	hdrs = [
		"stock.hh",
	],
	deps = [
		"//common:price",
		"//common:ticker",
	],
)
